db:
 image: postgres
 environment:
 - POSTGRES_USER=docker
 - POSTGRES_PASSWORD=docker
 - POSTGRES_DB=geogit
 entrypoint: /docker-entrypoint.sh
 command: postgres

geo:
 image: golang:onbuild
 command: /app/build_and_go.sh
 volumes:
   - .:/app
 links:
   - db
